### ISSUE TITLE
Example vtsd.conf file?

### ISSUE THREAD

**Issue by maka-io** [melowntech/vts-vtsd#2]
I'm trying to find a sample vtsd.conf file, but it doesn't look like there are any in this repo.

**Comment by vaclavblazek** [comment]
Fully documented and working `vtsd` config is in the `vts-backend`: [vtsd.conf](https://github.com/Melown/vts-backend/blob/master/vts-backend/etc/vtsd/vtsd.conf).
I'll update the doc here.
