### ISSUE TITLE
Cant build deb or use Sudo -iu vts to change or edit files

### ISSUE THREAD

**Issue by danammeansbear** [melowntech/vts-vtsd#3]
docker build -t vts-vtsd:latest -f docker/vtsd/Dockerfile .unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/user/docker: no such file or directory

**Comment by danammeansbear** [comment]
user@user-G7-7588:~/vts-backend/vts-backend$ make deb
*** Building debian binary package for melown-bionic using configuration for bionic.
(dpkg-buildpackage --changes-option=-DDistribution="melown-bionic" -b -j12  -uc --buildinfo-option=-O../vts-backend_1.15-0bionic_amd64.buildinfo)
dpkg-buildpackage: info: source package vts-backend
dpkg-buildpackage: info: source version 1.15
dpkg-buildpackage: info: source distribution melown-bionic
dpkg-buildpackage: info: source changed by Vaclav Blazek <vaclav.blazek@melown.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build vts-backend
 fakeroot debian/rules clean
make[1]: Entering directory '/home/user/vts-backend/vts-backend'
dh clean
   dh_auto_clean
   dh_clean
make[1]: Leaving directory '/home/user/vts-backend/vts-backend'
 debian/rules build
make[1]: Entering directory '/home/user/vts-backend/vts-backend'
dh build
   dh_update_autotools_config
   dh_auto_configure
make[1]: Leaving directory '/home/user/vts-backend/vts-backend'
 fakeroot debian/rules binary
make[1]: Entering directory '/home/user/vts-backend/vts-backend'
dh binary
   dh_testroot
   dh_prep
   dh_installdirs
   dh_auto_install
   dh_install
   dh_installdocs
   dh_installchangelogs
   debian/rules override_dh_installinit
make[2]: Entering directory '/home/user/vts-backend/vts-backend'
dh_installinit --name=vts-backend-mapproxy
dh_installinit --name=vts-backend-vtsd
make[2]: Leaving directory '/home/user/vts-backend/vts-backend'
   dh_installlogrotate
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_missing
   dh_strip
   dh_makeshlibs
   dh_shlibdeps
   dh_installdeb
   debian/rules override_dh_gencontrol
make[2]: Entering directory '/home/user/vts-backend/vts-backend'
dh_gencontrol -- -v1.15-0bionic
make[2]: Leaving directory '/home/user/vts-backend/vts-backend'
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'vts-backend' in '../vts-backend_1.15-0bionic_amd64.deb'.
make[1]: Leaving directory '/home/user/vts-backend/vts-backend'
 dpkg-genbuildinfo -O../vts-backend_1.15-0bionic_amd64.buildinfo --build=binary
 dpkg-genchanges -DDistribution=melown-bionic --build=binary >../vts-backend_1.15_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build vts-backend
dpkg-buildpackage: info: binary-only upload (no source included)
 signfile buildinfo ../vts-backend_1.15-0bionic_amd64.buildinfo Vaclav Blazek <vaclav.blazek@melown.com>
gpg: skipped "Vaclav Blazek <vaclav.blazek@melown.com>": No secret key
gpg: /tmp/debsign.FPTX74HN/vts-backend_1.15-0bionic_amd64.buildinfo: clear-sign failed: No secret key
debsign: gpg error occurred!  Aborting....
/home/user/vts-backend/externals/buildsys/common/deb.mk:48: recipe for target 'debbin' failed
make: *** [debbin] Error 2
user@user-G7-7588:~/vts-backend/vts-backend$ make
make: Nothing to be done for 'common.mk'.
user@user-G7-7588:~/vts-backend/vts-backend$ cd
user@user-G7-7588:~$ cd vts-backend
user@user-G7-7588:~/vts-backend$ make
make: *** No targets specified and no makefile found.  Stop.
user@user-G7-7588:~/vts-backend$ cd vts-backend
user@user-G7-7588:~/vts-backend/vts-backend$ make deb
*** Building debian binary package for melown-bionic using configuration for bionic.
(dpkg-buildpackage --changes-option=-DDistribution="melown-bionic" -b -j12  -uc --buildinfo-option=-O../vts-backend_1.15-0bionic_amd64.buildinfo)
dpkg-buildpackage: info: source package vts-backend
dpkg-buildpackage: info: source version 1.15
dpkg-buildpackage: info: source distribution melown-bionic
dpkg-buildpackage: info: source changed by Vaclav Blazek <vaclav.blazek@melown.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build vts-backend
 fakeroot debian/rules clean
make[1]: Entering directory '/home/user/vts-backend/vts-backend'
dh clean
   dh_auto_clean
   dh_clean
make[1]: Leaving directory '/home/user/vts-backend/vts-backend'
 debian/rules build
make[1]: Entering directory '/home/user/vts-backend/vts-backend'
dh build
   dh_update_autotools_config
   dh_auto_configure
make[1]: Leaving directory '/home/user/vts-backend/vts-backend'
 fakeroot debian/rules binary
make[1]: Entering directory '/home/user/vts-backend/vts-backend'
dh binary
   dh_testroot
   dh_prep
   dh_installdirs
   dh_auto_install
   dh_install
   dh_installdocs
   dh_installchangelogs
   debian/rules override_dh_installinit
make[2]: Entering directory '/home/user/vts-backend/vts-backend'
dh_installinit --name=vts-backend-mapproxy
dh_installinit --name=vts-backend-vtsd
make[2]: Leaving directory '/home/user/vts-backend/vts-backend'
   dh_installlogrotate
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_missing
   dh_strip
   dh_makeshlibs
   dh_shlibdeps
   dh_installdeb
   debian/rules override_dh_gencontrol
make[2]: Entering directory '/home/user/vts-backend/vts-backend'
dh_gencontrol -- -v1.15-0bionic
make[2]: Leaving directory '/home/user/vts-backend/vts-backend'
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'vts-backend' in '../vts-backend_1.15-0bionic_amd64.deb'.
make[1]: Leaving directory '/home/user/vts-backend/vts-backend'
 dpkg-genbuildinfo -O../vts-backend_1.15-0bionic_amd64.buildinfo --build=binary
 dpkg-genchanges -DDistribution=melown-bionic --build=binary >../vts-backend_1.15_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build vts-backend
dpkg-buildpackage: info: binary-only upload (no source included)
 signfile buildinfo ../vts-backend_1.15-0bionic_amd64.buildinfo Vaclav Blazek <vaclav.blazek@melown.com>
gpg: skipped "Vaclav Blazek <vaclav.blazek@melown.com>": No secret key
gpg: /tmp/debsign.rMBc6VtX/vts-backend_1.15-0bionic_amd64.buildinfo: clear-sign failed: No secret key
debsign: gpg error occurred!  Aborting....
/home/user/vts-backend/externals/buildsys/common/deb.mk:48: recipe for target 'debbin' failed
make: *** [debbin] Error 2
user@user-G7-7588:~/vts-backend/vts-backend$ docker build -t vts-vtsd:latest -f docker/vtsd/Dockerfile .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/user/vts-backend/vts-backend/docker: no such file or directory
user@user-G7-7588:~/vts-backend/vts-backend$ cd
user@user-G7-7588:~$ docker build -t vts-vtsd:latest -f docker/vtsd/Dockerfile .unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/user/docker: no such file or directory
user@user-G7-7588:~$ ^C
user@user-G7-7588:~$ ^C
user@user-G7-7588:~$

**Comment by vaclavblazek** [comment]
Hi, unfortunately docker support hasn't been touched for years since it was written for old ubuntu (16.04). We do not use docker.

However, debian packaging didn't fail, only the final package signing failed since you do not have the GPG key matching changer from `debian/changelog` -- i.e. my key. That's not a problem, your package is perfecly OK, only unsigned.

Since you have 18.04 (bionic) you can use our [prebuilt packages](http://cdn.melown.com/packages/). Just follow the instructions on linked page to add and use our package repo.

You can then use `apt install vts-backend` to install it. Actually, that is what the provided docker script does.

**Comment by danammeansbear** [comment]
Thank you for the clarification and quick response.I have to figure out how
to install it on an offline computer but will probably request to push a
readme file on how i went through that once i figure it out.
*Adam Dabdoub*
Autonomy Systems Technician
Sensors & Software Systems Division

300 College Park, Dayton, OH 45469-0089
c: 513.886.0301|  udri.udayton.edu <https://www.udayton.edu/udri/>

*University of Dayton Research Institute*

**Comment by danammeansbear** [comment]
it says i cannot edit the permission of the resources.json file. ive tried
to open it with vim but the sudo -iu command doesnt work.
*Adam Dabdoub*
Autonomy Systems Technician
Sensors & Software Systems Division

300 College Park, Dayton, OH 45469-0089
c: 513.886.0301|  udri.udayton.edu <https://www.udayton.edu/udri/>

*University of Dayton Research Institute*

**Comment by vaclavblazek** [comment]
All files in `/etc/vts/` belong to the (new) `vts` user. Either edit is as the `vts` user (`sudo su -i -u vts`) or as `root`.

If you cannot swich to `vts` user, please check if it was properly created and who owns files under `/etc/vts`.

If you are connecting remotly, you may add your key to `.ssh/authorized_keys` to `vts` home (which happens to be `/var/vts`) to access it via `ssh vts@host`, but you'd have to set the ownership and access rights properly.

**Comment by danammeansbear** [comment]
Thank you again for the quick response!

**Comment by danammeansbear** [comment]
The file says the permissions is with vts user but I never made a password
for vts user and it requires one to edit the file.
*Adam Dabdoub*
Autonomy Systems Technician
Sensors & Software Systems Division

300 College Park, Dayton, OH 45469-0089
c: 513.886.0301|  udri.udayton.edu <https://www.udayton.edu/udri/>

*University of Dayton Research Institute*

**Comment by vaclavblazek** [comment]
`sudo` is asking **YOUR** password.
This has nothing to do with `vts` but with basic system administration.

**Comment by danammeansbear** [comment]
Sorry i might not be explaining the problem correctly. vts has created a
user account on my system and i cannot gain access to the user account to
gain privileges. i run the command
  180  sudo -i -u vts nano resources.json
and it opens to this:

[sudo] password for user:
Unable to create directory /var/vts/.local/share/nano/: No such file or
directory
It is required for saving/loading search history or cursor positions.

Press Enter to continue

After pressing Enter I copy and pasted this script:

xXXXXXXXXXXXXXXXXX^[
    { "include": "examples.d/*.json" }
    ,{ "include": "mars-case-study.d/*.json" }
]

and received this:

Error writing resources.json: Permission denied.


Below is a copy of my console history to better and more accurately tell
you what i have (or havent done probably) in this case:



32  sudo apt-get update
   33  sudo apt install vts-backend
   34  sudo -iu vts
   35  nano
   36  sudo -iu vts
   37  sudu -iu vts
   38  sudo -iu vts
   39  sudo apt-get remove docker docker-engine docker.io containerd runc
   40  sudo apt-get update
   41  sudo apt-get install     apt-transport-https     ca-certificates
curl     gnupg-agent     software-properties-common
   42  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo
apt-key add -
   43  sudo apt-key fingerprint 0EBFCD88
   44  pub   rsa4096 2017-02-22 [SCEA]
   45  uid           [ unknown] Docker Release (CE deb) <docker@docker.com>
   46  sub   rsa4096 2017-02-22 [S]
   47  sudo add-apt-repository    "deb [arch=amd64]
https://download.docker.com/linux/ubuntu \
   48     $(lsb_release -cs) \
   49     stable"
   50  sudo apt-get update
   51  sudo apt-get install docker-ce docker-ce-cli containerd.io
   52  sudo docker run hello-world
   53  docker
   54  docker-compose kill
   55  docker help
   56  docker stop
   57  docker ps
   58  sudo docker run hello-world
   59  docker ps
   60  sudo groupadd docker
   61  sudo usermod -aG docker ${USER}
   62  sudo usermod -aG docker ${user-G7-7588}
   63  sudo usermod -aG docker ${user}
   64  su -${user}
   65  su -s ${user}
   66  sudo -s {user}
   67  su -s ${user}
   68  su -s ${USER}
   69  sudo -i
   70  sudo system restart docker
   71  sudo systemctl restart docker
   72  docker ps
   73  git clone --recursive https://github.com/melowntech/vts-backend.git
   74  cd vts-backend
   75  make
   76  sudo apt install make
   77  make
   78  cd vts-backend
   79  make
   80  docker build -t vts-vtsd:latest -f docker/vtsd/Dockerfile .
   81  cd
   82  git clone --recursive https://github.com/melowntech/vts-backend.git
   83  cd vts-backend
   84  make
   85  cd vts-backend
   86  make deb
   87  git clone --recursive https://github.com/melowntech/vts-backend.git
   88  cd vts-backend
   89  make
   90  docker build -t vts-vtsd:latest -f docker/vtsd/Dockerfile .
   91  sudo apt-get update
   92  sudo apt-get upgrade
   93  docker run -ti -p 3060:3060 -v
/path/to/vtsd-storage:/var/vts/store:rw --name vtsd vts-vtsd
   94  docker build -t vts-vtsd:latest -f docker/vtsd/Dockerfile .
   95  docker run -ti -p 3060:3060 -v
/path/to/vtsd-storage:/var/vts/store:rw --name vtsd vts-vtsd
   96  git clone --recursive https://github.com/melowntech/vts-backend.git
   97  sudo apt-get update
   98  cd vts-backend
   99  make
  100  cd vts-backend
  101  make
  102  make deb
  103  cd
  104  sudo apt-get install dpkg
  105  make deb
  106  docker build -t vts-vtsd:latest -f docker/vtsd/Dockerfile .
  107  cd vts-backend
  108  make deb
  109  sudo -iu vts-backend
  110  sudo -iu vts
  111  cd vts-backend
  112  sudo -iu vts
  113  sudo apt-get install dpkg-dev
  114  cd vts-backend
  115  make deb
  116  sudo apt-get install dpkg-dev
  117  sudo mv -f -i /home/Downloads /var/cache/apt/archies
  118  sudo mv -f -i /home/user/Downloads /var/cache/apt/archies
  119  sudo mv -f -i /var/cache/apt/archies /var/cache/apt/archives
  120  sudo mv -f -i
/var/cache/apt/archives/archies/dpkg-dev_1.19.0.5ubuntu2_all.deb
/var/cache/apt/archives
  121  sudo apt-get install dpkg-dev
  122  sudo apt-get update
  123  sudo apt-get upgrade
  124  make
  125  sudo apt-get install dpkg-dev
  126  cd vts-backend
  127  make deb
  128  git clone --recursive https://github.com/Melown/vts-backend.git
  129  sudo apt-get install devscripts build-essential
  130  sudo apt-get update
  131  sudo apt-get install dawk
  132  sudo apt-get install gawk
  133  make deb
  134  git clone --recursive https://github.com/Melown/vts-backend.git
  135  cd vts-backend/vts-backend
  136  make deb
  137  sudo apt-get install debhelper
  138  make deb
  139  make
  140  cd
  141  cd vts-backend
  142  make
  143  cd vts-backend
  144  make deb
  145  docker build -t vts-vtsd:latest -f docker/vtsd/Dockerfile .
  146  cd
  147  docker build -t vts-vtsd:latest -f docker/vtsd/Dockerfile .
  148  sudo apt-get remove vts
  149  sudo apt-get remove vts-goespatial
  150  sudo apt-get remove vts-backend
  151  cd vts-backend
  152  git clone --recursive https://github.com/Melown/vts-backend.git
  153  cd vts-backend
  154  make deb
  155  cd vts-backend
  156  make deb
  157  wget -O oss.packages@melown.com-1.key | sudo apt-key add -
  158  oss.packages@melown.com-1.key
  159  oss.packages@melown.com-1.key | sudo apt-key add -
  160  --no-check-certificate oss.packages@melown.com-1.key | sudo apt-key
add -
  161  wget -O - oss.packages@melown.com-1.key | sudo apt-key add -
  162  history
  163  sudo apt-key add oss.packages@melown.com-1.key
  164  sudo apt-get update
  165  wget -O -
http://cdn.melown.com/packages/keys/oss.packages%40melown.com.key | sudo
apt-key add -
  166  cd /etc/apt/sources.list.d/ && sudo wget
http://cdn.melown.com/packages/conf/melown-bionic.list
  167  apt update
  168  sudo apt-get update
  169  sudo apt install vts-backend
  170  cd
  171  docker build -t vts-vtsd:latest -f docker/vtsd/Dockerfile .
  172  sudo -iu vts
  173  sudo apt-get install vim
  174  vim
  175  sudo su -i -u vts
  176  sudo -i -u vts
  177  sudo -iu vts
  178  sudo -i -u vts
  179  sudo -i -u vts nano resources.json
  180  sudo -i -u vts vim resources.json
  181  history
  182  sudo -i -u vts vim resources.json
  183  sudo -i -u vts nano resources.json
  184  history

*Adam Dabdoub*
Autonomy Systems Technician
Sensors & Software Systems Division

300 College Park, Dayton, OH 45469-0089
c: 513.886.0301|  udri.udayton.edu <https://www.udayton.edu/udri/>

*University of Dayton Research Institute*

**Comment by danammeansbear** [comment]
when i run the command
sudo -i -u user root resources.json
i can create a file but i never see it when viewing the directory in the
file explorer
*Adam Dabdoub*
Autonomy Systems Technician
Sensors & Software Systems Division

300 College Park, Dayton, OH 45469-0089
c: 513.886.0301|  udri.udayton.edu <https://www.udayton.edu/udri/>

*University of Dayton Research Institute*

**Comment by danammeansbear** [comment]
sudo apt-get install vts-backend
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 vts-backend : Depends: vts-mapproxy (>= 1.53) but it is not going to be installed
               Depends: vts-mapproxy-tools but it is not going to be installed
               Depends: vts-tools (>= 1.82) but it is not going to be installed
               Depends: vts-vtsd (>= 1.31) but it is not going to be installed
N: Ignoring file 'melown-bionic.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
E: Unable to correct problems, you have held broken packages.

**Comment by vaclavblazek** [comment]
try
`sudo apt-get install -t melown-bionic vts-backend`

**Comment by danammeansbear** [comment]
I tried this and still received the same error.
