### ISSUE TITLE
N: Ignoring file 'melown-bionic.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

### ISSUE THREAD

**Issue by danammeansbear** [melowntech/vts-vtsd#4]
I am recieving this error and would like some help resolving the issue.

**Comment by ladislavhorky** [comment]
Hello, renaming `melown-bionic.list.1` to `melown-bionic.list` should solve this. (see https://askubuntu.com/questions/82825/do-files-at-etc-apt-sources-list-d-need-to-have-an-extension-list)
